[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/jingyanghjy/huangjy-blog"
  weight = 40